name = "StaTech Industry"
author = "static"
version = "1.1.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f74dba9ee9f7ee69b91a5657e389707d6832f70a5c1418b3c2b4c35fbba3d1e"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
