name = "StaTech Industry"
author = "staitc"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d022de8864dea733bebb44b4266288755153d6f883cb0ee0ad896c7fcd5d633"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.92"
