name = "StaTech Industry"
author = "static"
version = "1.1.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a042703c8b6997aace2c99b29d9c3f1324e37e32e5782e4a4df1c4843864dc1e"

[versions]
fabric = "0.16.9"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
