name = "StaTech Industry"
author = "static"
version = "1.1.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8db5530511d127bf9e67d560e9994930b430cb7778ed9c2bbe74883a60a874d5"

[versions]
fabric = "0.16.9"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
