name = "StaTech Industry"
author = "staitc"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7843cbd9bdeb4558ff3a5032723de5e4cadacd9780a625aefa4b14a7b764c8c"

[versions]
minecraft = "1.21"
neoforge = "21.0.133-beta"
