name = "StaTech Industry"
author = "static"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e804813646544245dd899f75f3486154e83de491890ee264826e391ecf2bcdcb"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
