name = "StaTech Industry"
author = "static"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbad3078c1502330758041aeeb8ef33b1ce8645c778474025c3514ac53bbdeaf"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
